export const SEED_PATIENTS = [
  {
    id: "a0111111-1111-1111-1111-111111111111",
    fhirId: "patient-kenya-001",
    nationalId: "29482103",
    firstName: "Wanjiku",
    lastName: "Mwangi",
    dateOfBirth: "1988-04-14",
    gender: "female",
    phone: "+254 722 123 456",
    email: "wanjiku.mwangi@example.co.ke",
    county: "Nairobi (Westlands)",
    emergencyContact: "Kamau Mwangi (+254 722 987 654)",
    consentStatus: "active",
    lawfulBasis: "Kenya_DPA_Sec_32_Explicit_Consent",
    allowClinicalSharing: true,
    diagnosis: "Type 2 Diabetes Mellitus with Mild Hypertension",
    clinicalNotes: "Patient reports improved fasting glucose with Metformin 500mg BD. Counseled on dietary adjustments suitable for local carbohydrate staples.",
    prescriptions: "Metformin 500mg BD x 90 days, Enalapril 5mg OD",
    vitals: { bp: "128/82 mmHg", heartRate: 74, temp: "36.7 C", weightKg: 68 },
  },
  {
    id: "b0222222-2222-2222-2222-222222222222",
    fhirId: "patient-kenya-002",
    nationalId: "33890124",
    firstName: "Otieno",
    lastName: "Ochieng",
    dateOfBirth: "1994-11-23",
    gender: "male",
    phone: "+254 733 456 789",
    email: "otieno.ochieng@example.co.ke",
    county: "Nairobi (Kilimani)",
    emergencyContact: "Achieng Ochieng (+254 733 112 233)",
    consentStatus: "active",
    lawfulBasis: "Kenya_DPA_Sec_32_Explicit_Consent",
    allowClinicalSharing: true,
    diagnosis: "Acute Bronchial Asthma Exacerbation",
    clinicalNotes: "Presented to triage with wheezing and shortness of breath following cold weather in Nairobi. Nebulized with Salbutamol with good recovery.",
    prescriptions: "Salbutamol Inhaler 100mcg 2 puffs PRN, Prednisolone 30mg OD x 5 days",
    vitals: { bp: "120/80 mmHg", heartRate: 88, temp: "37.0 C", weightKg: 75 },
  },
  {
    id: "c0333333-3333-3333-3333-333333333333",
    fhirId: "patient-kenya-003",
    nationalId: "18920475",
    firstName: "Fatuma",
    lastName: "Hassan",
    dateOfBirth: "1976-08-05",
    gender: "female",
    phone: "+254 710 998 877",
    email: "fatuma.hassan@example.co.ke",
    county: "Mombasa (Nyali)",
    emergencyContact: "Ali Hassan (+254 710 334 455)",
    consentStatus: "restricted", // Restricted consent under Kenya DPA
    lawfulBasis: "Kenya_DPA_Sec_32_Partial_Restriction",
    allowClinicalSharing: false,
    diagnosis: "Confidential: Chronic Thyroiditis (Under Investigation)",
    clinicalNotes: "Patient has requested restricted processing under Kenya DPA Section 26(d). Records restricted from inter-clinic sharing.",
    prescriptions: "Levothyroxine 50mcg OD",
    vitals: { bp: "135/88 mmHg", heartRate: 66, temp: "36.5 C", weightKg: 62 },
  },
  {
    id: "d0444444-4444-4444-4444-444444444444",
    fhirId: "patient-kenya-004",
    nationalId: "38910482",
    firstName: "Kipchumba",
    lastName: "Ruto",
    dateOfBirth: "2001-02-18",
    gender: "male",
    phone: "+254 701 556 677",
    email: "kipchumba.ruto@example.co.ke",
    county: "Uasin Gishu (Eldoret)",
    emergencyContact: "Chebet Ruto (+254 701 223 344)",
    consentStatus: "revoked", // Revoked consent test case
    lawfulBasis: "Consent_Revoked_By_Data_Subject",
    allowClinicalSharing: false,
    diagnosis: "Right Ankle Lateral Ligament Sprain (Athletic)",
    clinicalNotes: "Patient revoked third-party analytics & clinical research consent on 2026-09-10. Clinical care ongoing under direct medical contract.",
    prescriptions: "Ibuprofen 400mg TDS PRN, Ankle brace immobilization",
    vitals: { bp: "118/75 mmHg", heartRate: 58, temp: "36.6 C", weightKg: 69 },
  }
];

export const SEED_USERS = [
  {
    id: "doc-kamau-01",
    email: "dr.kamau@afyasecure.health",
    fullName: "Dr. Evans Kamau, MD",
    role: "DOCTOR",
    department: "Internal Medicine",
  },
  {
    id: "nurse-amina-02",
    email: "nurse.amina@afyasecure.health",
    fullName: "Nurse Amina Mohamed, BSN",
    role: "NURSE",
    department: "Outpatient Triage",
  },
  {
    id: "rec-brian-03",
    email: "brian.odhiambo@afyasecure.health",
    fullName: "Brian Odhiambo",
    role: "RECEPTIONIST",
    department: "Patient Registration & Front Desk",
  },
  {
    id: "dpo-sarah-04",
    email: "dpo.njeri@afyasecure.health",
    fullName: "Adv. Sarah Njeri, CIPP/E",
    role: "DPO_AUDITOR",
    department: "Legal & Data Protection Office",
  },
];
